# Generated by Django 6.0.3 on 2026-05-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_alter_patient_doctor_delete_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='discharged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_discharged',
            field=models.BooleanField(default=False),
        ),
    ]
