# Generated by Django 6.0.3 on 2026-05-18 07:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_patient_discharged_at_patient_is_discharged'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='admitted_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='address',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='ward',
        ),
        migrations.AlterField(
            model_name='patient',
            name='doctor',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
